project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  back-to-top-navigation: true
  comments: 
    utterances:
      repo: vidyasagarbhargava/vidyasagarbhargava.github.io
      issue-term: title
  favicon: images/logo.svg
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: myblog/blog.qmd
        text: Blog
      - href: research/research.qmd
        text: Research Papers
      - href: london.qmd
        text: London 
      - icon: rss
        href: index.xml
format:
  html:
    mainfont: system-ui
    fontsize: 95%
    theme: 
      light: [light.scss, cosmo]
      dark:  [dark.scss, darkly]
    css: styles.css
    toc: true

