project:
  type: website
  output-dir: docs
  render: 
    - '*.ipynb'
    - '!index.ipynb'

execute:
  freeze: true

website:
  title: "Vidyasagar Bhargava"
  back-to-top-navigation: true
  comments: 
    utterances:
      repo: vidyasagarbhargava/vidyasagarbhargava.github.io
      issue-term: title
  favicon: images/logo.svg
  site-url: 'https://vidyasagarbhargava.github.io'
  description: "Data Science & Machine Learning blog"
  navbar:
    right:
      - href: about.qmd
        text: About
      - href: index.qmd
        text: Blog
      - href: london.qmd
        text: London 
      - icon: rss
        href: index.xml
format:
  html:
    mainfont: system-ui
    fontsize: 95%
    theme: 
      light: [light.scss, cosmo]
      dark:  [dark.scss, darkly]
    css: styles.css
    toc: true

