project:
  type: website
  output-dir: docs

website:
  favicon: logo.svg
  navbar:
    right:
      - href: index.qmd
        text: HOME
      - href: myblog/blog.qmd
        text: BLOG
      - href: cv.qmd
        text: CV
      - href: london.qmd
        text: LONDON 

format:
  html:
    mainfont: system-ui
    fontsize: 90%
    theme: [none, theme.scss]
    backgroundcolor: "#e6ddde"
    css: styles.css
    toc: true


